### ISSUE TITLE
Console spamming

### ISSUE THREAD

**Issue by UNEXISDevelopment** [ScrachStack/qb-moneywash#3]
![Screenshot 2023-11-12 001822](https://github.com/Zaps6000/qb-moneywash/assets/106434295/a050741d-9525-4eda-aee9-3db168b22839)

it keeps spamming this to all players

**Comment by ScrachStack** [comment]
https://github.com/Zaps6000/qb-moneywash/commit/f32c54a492b111d2438be5f3608a7ca9703fbe1f refer to I think this is a issue with keymapping when command is renamed it sloves its self and no longer saids its not a command but I fixed it and updated the main branch

**Comment by ScrachStack** [comment]
https://github.com/Zaps6000/qb-moneywash/releases/tag/6.4
